/**
 * @file evaluate.h
 * @brief Defines the function to evaluate an expression AST within a given
 * scope.
 *
 * This takes an AST generated by the expression parser and computes its final
 * value using data from a context or scope object.
 */

#ifndef EVALUATE_H
#define EVALUATE_H

#include "../core/value.h"

/**
 * @brief Evaluates an expression AST.
 * @param node The root `Value` of the expression AST.
 * @param scope An object `Value` representing the data scope (e.g., component
 * state and props).
 * @return A new `Value` representing the result of the evaluation.
 */
Value *evaluate_expression(const Value *node, const Value *scope);

#endif // EVALUATE_H
